version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: neolink-postgres
    environment:
      POSTGRES_DB: neolink
      POSTGRES_USER: neolink
      POSTGRES_PASSWORD: neolink_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U neolink -d neolink']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: neolink-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # API 服务
  api:
    build:
      context: .
      target: development
    container_name: neolink-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://neolink:neolink_password@postgres:5432/neolink
      REDIS_URL: redis://redis:6379
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ['pnpm', '--filter=@neolink/api', 'dev']
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Web 前端
  web:
    build:
      context: .
      target: development
    container_name: neolink-web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    command: ['pnpm', '--filter=@neolink/web', 'dev']
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: neolink-network
